version: '3.7' 
services:
  app: 
    container_name: clientst
    image: clientstaging
    restart: always 
    build: .
    environment:
      - BRANCH=staging
      - ENVIRONMENT=st
    ports: 
    - '3030:3030'
    expose:
      - '3030'

  webapi: 
    container_name: serverst
    image: serverstaging
    restart: always 
    build: .
    environment:
      - BRANCH=staging
      - ENVIRONMENT=st
    ports: 
      - '3000:3000'
    expose:
      - '3000'  
    links:
      - mongost
    
  mongost:
    container_name: mongost
    image: mongodb/mongodb-community-server
    volumes: 
      - ./data:/data/db
    ports:
      - '27017:27019'