version: '3.7' 
services:
  app: 
    container_name: clientdev
    image: clientdevelop
    restart: always 
    build: .
    environment:
      - BRANCH=develop
      - ENVIRONMENT=dev
    ports: 
    - '2020:2020'
    expose:
      - '2020'

  webapi: 
    container_name: serverdev
    image: serverdevelop
    restart: always 
    build: .
    environment:
      - BRANCH=develop
      - ENVIRONMENT=dev
    ports: 
      - '2000:2000'
    expose:
      - '2000'  
    links:
      - mongodev
    
  mongodev:
    container_name: mongodev 
    image: mongodb/mongodb-community-server
    volumes: 
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongodb_data: