version: '3.7'
services:
  app:
    container_name: clientpro
    image: clientmain
    restart: always
    build: .
    environment:
      - BRANCH=main
      - ENVIRONMENT=pro
      - HOST=http://localhost
      - HOST_SERVER=http://nginxpro
      - PORT_SERVER=4000
    ports:
      - '4040:4040'
    expose:
      - '4040'
    networks:
      - pro-network
    links:
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040"]
      interval: 30s
      timeout: 10s
      retries: 3

  webapi1:
    container_name: serverpro1
    image: servermain
    restart: always
    build: .
    environment:
      - BRANCH=main
      - ENVIRONMENT=pro
    expose:
      - '4000'
    networks:
      - pro-network
    links:
      - mongopro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

  webapi2:
    container_name: serverpro2
    image: servermain
    restart: always
    build: .
    environment:
      - BRANCH=main
      - ENVIRONMENT=pro
    expose:
      - '4000'
    networks:
      - pro-network
    links:
      - mongopro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongopro:
    container_name: mongopro
    image: mongo:7.0.10-rc0-jammy
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - pro-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginxpro
    ports:
      - '4000:4000'
    expose:
      - '4000'
    volumes:
      - ./nginx/nginx-pro.conf:/etc/nginx/nginx.conf
    networks:
      - pro-network
    links:
      - webapi1
      - webapi2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheuspro
    volumes:
      - ./nginx/prometheus-pro.yml:/etc/prometheus/prometheus.yml
    ports:
      - '4444:9090'
    networks:
      - pro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '4440:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=edinson1
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - pro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  pro-network:
    name: pro-network
    driver: bridge

volumes:
  mongodb:
  grafana:
