version: '3.7'

services:
  app:
    container_name: clientpro
    image: clientmain
    restart: always
    build: .
    environment:
      - BRANCH=main
      - ENVIRONMENT=pro
    ports:
      - '4040:4040'
    expose:
      - '4040'
    networks:
      - pro-network

  webapi:
    container_name: serverpro
    image: servermain
    restart: always
    build: .
    environment:
      - BRANCH=main
      - ENVIRONMENT=pro
    ports:
      - '4000:4000'
    expose:
      - '4000'
    networks:
      - pro-network
    links:
      - mongopro

  mongopro:
    container_name: mongopro
    image: mongo:7.0.10-rc0-jammy
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - pro-network

networks:
  pro-network:
    name: pro-network
    driver: bridge

volumes:
  mongodb: