version: '3.7' 
services:
  app: 
    container_name: clientdev
    image: clientdevelop
    restart: always 
    build: .
    environment:
      - BRANCH=develop
      - ENVIRONMENT=dev
    ports: 
    - '2020:2020'
    expose:
      - '2020'
    networks:
      - dev-network

  webapi: 
    container_name: serverdev
    image: serverdevelop
    restart: always 
    build: .
    environment:
      - BRANCH=develop
      - ENVIRONMENT=dev
    ports: 
      - '2000:2000'
    expose:
      - '2000'  
    links:
      - mongodev
    networks:
      - dev-network
    
  mongodev:
    container_name: mongodev 
    image: mongo:7.0.10-rc0-jammy
    volumes: 
      - mongodb:/data/db
    ports:
      - '27017:27017'
    expose:
      - '27017' 
    networks:
      - dev-network
        

networks:
  dev-network:
    name: dev-network
    driver: bridge

volumes:
  mongodb: