version: '3.7'
services:
  app:
    container_name: clientdev
    image: clientdevelop
    restart: always
    build: .
    environment:
      - BRANCH=develop
      - ENVIRONMENT=dev
      - HOST=http://localhost
      - HOST_SERVER=http://nginxdev
      - PORT_SERVER=2000
    ports:
      - '2020:2020'
    networks:
      - dev-network
    links:
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2020"]
      interval: 30s
      timeout: 10s
      retries: 3

  webapi1:
    container_name: serverdev1
    image: serverdevelop
    restart: always
    build: .
    environment:
      - BRANCH=develop
      - ENVIRONMENT=dev
    expose:
      - '2000'
    networks:
      - dev-network
    links:
      - mongodev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000"]
      interval: 30s
      timeout: 10s
      retries: 3

  webapi2:
    container_name: serverdev2
    image: serverdevelop
    restart: always
    build: .
    environment:
      - BRANCH=develop
      - ENVIRONMENT=dev
    expose:
      - '2000'
    networks:
      - dev-network
    links:
      - mongodev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodev:
    container_name: mongodev
    image: mongo:7.0.10-rc0-jammy
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginxdev
    ports:
      - '2000:2000'
    expose:
      - '2000'
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    networks:
      - dev-network
    links:
      - webapi1
      - webapi2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheusdev
    volumes:
      - ./nginx/prometheus-dev.yml:/etc/prometheus/prometheus.yml
    ports:
      - '2222:9090'
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '2220:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=edinson1
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dev-network:
    name: dev-network
    driver: bridge

volumes:
  mongodb:
  grafana:
