version: '3.7' 
services:
  app: 
    container_name: clientst
    image: clientstaging
    restart: always 
    build: .
    environment:
      - BRANCH=staging
      - ENVIRONMENT=st
    ports: 
    - '3030:3030'
    expose:
      - '3030'
    networks:
      - st-network

  webapi: 
    container_name: serverst
    image: serverstaging
    restart: always 
    build: .
    environment:
      - BRANCH=staging
      - ENVIRONMENT=st
    ports: 
      - '3000:3000'
    expose:
      - '3000'
    networks:
      - st-network  
    links:
      - mongost
    
  mongost:
    container_name: mongost
    image: mongo:7.0.10-rc0-jammy
    volumes: 
      - mongodb:/data/db
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - st-network

networks:
  st-network:
    name: st-network
    driver: bridge

volumes:
  mongodb: