version: '3' 
services:
  app: 
    container_name: clientpro
    image: clientmain
    restart: always 
    build:
      args:
        - branch=main
    ports: 
    - '4040:4040'
    expose:
      - '4040'

  webapi: 
    container_name: serverpro
    image: servermain
    restart: always 
    build:
      args:
        - branch=main
    ports: 
      - '4000:4000'
    expose:
      - '4000'  
    links:
      - mongo
    
  mongo:
    container_name: mongo 
    image: mongodb/mongodb-community-server
    volumes: 
      - ./data:/data/db
    ports:
      - '27017:27017'