global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:4444']

  - job_name: 'webapi1'
    static_configs:
      - targets: ['webapi1:4000']

  - job_name: 'webapi2'
    static_configs:
      - targets: ['webapi2:4000']

  - job_name: 'mongopro'
    static_configs:
      - targets: ['mongopro:27017']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginxpro:4000']
